version: "3.8"

services:
  spring:
    build: ./backend
    container_name: backend
    image: backend
    expose:
      - "8080"
    ports:
     - 8080:8080
    restart: always
    networks:
      - pintogether-net

  next:
    build: ./frontend
    container_name: frontend
    image: frontend
    ports:
     - 3000:3000
    expose:
     - "3000"
    restart: always
    networks:
     - pintogether-net

  nginx:
    image: nginx:1.21.5-alpine
    container_name: nginx
    ports:
     - 8000:8000
    volumes:
     - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
     - next
     - spring
    networks:
     - pintogether-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - pintogether-net
networks:
  pintogether-net:
    driver: bridge
