global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring'
    static_configs:
      - targets: ['backend:8080']

  - job_name: 'next'
    static_configs:
      - targets: ['frontend:3000']

